name: Fx.TextMorph
author: nicodmf
category: Effects
tags: [effects, morph, text]
current: 1.0
docs: http://github.com/ndmf/TextMorphMootools/blob/master/README.md
demo: http://ndmf.github.com/TextMorph/demos/mootoolsDemo.html