name: Fx.TextMorph
author: nicodmf
category: Effects
tags: [effects, morph, text]
current: 1.0
docs: http://github.com/nicodmf/TextMorphMootools/blob/master/README.md
demo: http://nicodmf.github.com/TextMorphMootools/