name: Fx.TextMorph
author: nicodmf
category: Effects
tags: [effects, morph, text]
current: 1.0.0
docs: http://github.com/vincentbluff/Fx.MorphElement/blob/master/README.md
demo: http://vincentbluff.github.com/Fx.MorphElement